services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - notes-net

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: notes
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    expose:
      - 3306:3306
    networks:
      - notes-net

networks:
  notes-net:
    driver: bridge

